# Generated by Django 4.0 on 2021-12-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=250)),
                ('Product_description', models.TextField(null=True)),
                ('End_Time', models.DateTimeField(null=True)),
            ],
        ),
    ]
